### ISSUE TITLE
Bug: pip install simsimd error under the gcc14.2 version

### ISSUE THREAD

**Issue by kukugpt** [ashvardanian/SimSIMD#229]
### Describe the bug

Collecting simsimd
  Downloading https://mirrors.aliyun.com/pypi/packages/0d/3e/f68bdc6659896b2c6f715c4ee2c02dd76a5a0d5d97c062daa81884493fee/simsimd-6.0.1.tar.gz (155 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: simsimd
  Building wheel for simsimd (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for simsimd (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      running bdist_wheel
      running build
      running build_py
      running egg_info
      writing simsimd.egg-info/PKG-INFO
      writing dependency_links to simsimd.egg-info/dependency_links.txt
      writing top-level names to simsimd.egg-info/top_level.txt
      reading manifest file 'simsimd.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'simsimd.egg-info/SOURCES.txt'
      creating build/lib.linux-x86_64-cpython-311/simsimd
      copying python/annotations/__init__.pyi -> build/lib.linux-x86_64-cpython-311/simsimd
      copying python/annotations/py.typed -> build/lib.linux-x86_64-cpython-311/simsimd
      running build_ext
      building 'simsimd' extension
      creating build/temp.linux-x86_64-cpython-311/c
      creating build/temp.linux-x86_64-cpython-311/python
      /usr/local/bin/gcc -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /search/ai/harryzhtang/anaconda3/envs/mmsegment/include -fPIC -O2 -isystem /search/ai/harryzhtang/anaconda3/envs/mmsegment/include -fPIC -DSIMSIMD_NATIVE_F16=0 -DSIMSIMD_NATIVE_BF16=0 -DSIMSIMD_DYNAMIC_DISPATCH=1 -DSIMSIMD_TARGET_NEON=1 -DSIMSIMD_TARGET_NEON_F16=1 -DSIMSIMD_TARGET_NEON_BF16=1 -DSIMSIMD_TARGET_SVE=1 -DSIMSIMD_TARGET_SVE_F16=1 -DSIMSIMD_TARGET_SVE_BF16=1 -DSIMSIMD_TARGET_SVE2=1 -DSIMSIMD_TARGET_HASWELL=1 -DSIMSIMD_TARGET_SKYLAKE=1 -DSIMSIMD_TARGET_ICE=1 -DSIMSIMD_TARGET_GENOA=1 -DSIMSIMD_TARGET_SAPPHIRE=1 -DSIMSIMD_TARGET_TURIN=1 -DSIMSIMD_TARGET_SIERRA=0 -Iinclude -I/search/ai/harryzhtang/anaconda3/envs/mmsegment/include/python3.11 -c c/lib.c -o build/temp.linux-x86_64-cpython-311/c/lib.o -std=c11 -O3 -ffast-math -fdiagnostics-color=always -fvisibility=default -fPIC -w -fopenmp
      In file included from /usr/include/math.h:419,
                       from include/simsimd/types.h:246,
                       from include/simsimd/binary.h:21,
                       from include/simsimd/simsimd.h:105,
                       from c/lib.c:48:
      /usr/include/bits/math-finite.h: In function ‘lgamma’:
      /usr/include/bits/math-finite.h:261:10: error: implicit declaration of function ‘lgamma_r’; did you mean ‘lgammal’? [-Wimplicit-function-declaration]
        261 |   return lgamma_r (__d, &__local_signgam);
            |          ^~~~~~~~
            |          lgammal
      /usr/include/bits/math-finite.h: In function ‘lgammaf’:
      /usr/include/bits/math-finite.h:270:10: error: implicit declaration of function ‘lgammaf_r’; did you mean ‘lgammaf’? [-Wimplicit-function-declaration]
        270 |   return lgammaf_r (__d, &__local_signgam);
            |          ^~~~~~~~~
            |          lgammaf
      /usr/include/bits/math-finite.h: In function ‘lgammal’:
      /usr/include/bits/math-finite.h:280:10: error: implicit declaration of function ‘lgammal_r’; did you mean ‘lgammal’? [-Wimplicit-function-declaration]
        280 |   return lgammal_r (__d, &__local_signgam);
            |          ^~~~~~~~~
            |          lgammal
      error: command '/usr/local/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simsimd
Failed to build simsimd
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (simsimd)

### Steps to reproduce

 gcc==14.2
python==3.11

### Expected behavior

build error

### SimSIMD version

6.0.1

### Operating System

CenterOS

### Hardware architecture

x86

### Which interface are you using?

Python bindings

### Are you open to being tagged as a contributor?

- [X] I am open to being mentioned in the project `.git` history as a contributor

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ashvardanian** [comment]
Thanks, @kukugpt! A patch is coming 🤗

**Comment by Sakura4036** [comment]
`pip install simsimd`(v6.0.3) failed, still not work in `Ubuntu 18.04 glibc v2.27`

**Comment by saitros** [comment]
Hi i have same issue, in `Ubuntu 18.04 gcc 13.01`.
But i found my cpu didnt support `AVX-512 BF16` flag.

During compilation, errors related to instructions like `vfmadd231ph` or `vaddph` occurred, and the issue was identified as the CPU not supporting these instructions.

By running the following command in bash:
`lscpu | grep Flags`

It was confirmed that the following two operation flags are missing:

- avx512f (AVX-512 Foundation instructions)

- avx512bf16 (BFloat16 operations)

My CPU is an Intel(R) Core(TM) i9-10980XE.

**Comment by ashvardanian** [comment]
With the recent compiler the compilation should still pass. It doesn't matter that your CPU doesn't support those instructions, @saitros. Just make sure it uses the right intrinsic headers.

**Comment by xsonwong** [comment]
> With the recent compiler the compilation should still pass. It doesn't matter that your CPU doesn't support those instructions, [@saitros](https://github.com/saitros). Just make sure it uses the right intrinsic headers.

Seems not working with GCC 12.4...
